[window]
padding = { x = 24, y = 24 }

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
bold = { family = "DejaVuSansM Nerd Font Mono", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font Mono", style = "Oblique" }
size = 12.0

[general]
import = [
    "~/proj/colsync/output/alacritty/colsync.toml"
]
